name: CI

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}
      - if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}
      - run: npm run lint
  unit-test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}
      - run: npm test
